routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index');

Route::group(['middleware'=>'auth'],function(){


    Route::resource('article','ArticleController');
});

app/Article.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Article extends Model
{
    //setting mass assignment
    protected $fillable=[
        'title','description','body'
    ];

    //creating relationships

    //$article->user()
    public function User(){
        return $this->belongsTo(User::class);
//        return $this->belongsTo('\App\User','id','user_id');
    }
}

app/Comment.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Comment extends Model
{
    protected $fillable=[
        'body'
    ];

    public function User(){
        return $this->belongsTo(User::class);
//        return $this->belongsTo('\App\User','id','user_id');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    use SoftDeletes;

    //defining realtionships

    public function Article(){
        return $this->hasMany(Article::class);
    }
}

app/Http/Controllers/ArticleController.php
<?php

namespace App\Http\Controllers;

use App\Article;
use App\Http\Requests\ArticleRequest;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Symfony\Component\Yaml\Tests\A;

class ArticleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $articles = Article::with('User')->latest()->get();
//        dd($articles);
        return view('welcome',compact('articles'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('articles.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ArticleRequest $request)
    {
      $data= new Article();
        $data->user_id =Auth::user()->id;
        $data->title =$request->title;
        $data->body =$request->body;
        $data->description =$request->description;
        $data->save();
        \Session::flash('success','Article created successfully');
        return redirect(route('article.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/CommentController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class CommentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

resources/views/articles/create.blade.php
@extends('layouts.theme')

@section('working_area')

    <div class="col-lg-6">
        <div class="card-box col-md-offset-3">
            {!! Form::open(['route'=>'article.store','class'=>'form form-horizontal']) !!}
            <div class="form-group {{ $errors->has('title') ? ' has-error' : '' }}">
                {!! Form::label('title','Title',null,['class'=>'control-label']) !!}
                {!! Form::text('title',null,['class'=>'form-control' ]) !!}
                @if ($errors->has('title'))
                    <span class="help-block">
                        <strong>{{ $errors->first('title') }}</strong>
                    </span>
                @endif
                </div>
            <div class="form-group {{ $errors->has('description') ? ' has-error' : '' }}">

            {!! Form::label('desc','Description',null,['class'=>'control-label']) !!}
                {!! Form::text('description',null,['class'=>'form-control']) !!}
                @if ($errors->has('description'))
                    <span class="help-block">
                                        <strong>{{ $errors->first('description') }}</strong>
                                    </span>
                @endif
                </div>
            <div class="form-group {{ $errors->has('body') ? ' has-error' : '' }}">

            {!! Form::label('body','Body',null,['class'=>'control-label']) !!}
                {!! Form::textarea('body',null,['class'=>'form-control']) !!}
                @if ($errors->has('body'))
                    <span class="help-block">
                                        <strong>{{ $errors->first('body') }}</strong>
                                    </span>
                @endif
            </div>
                {!! Form::submit('Create Article',['class'=>'btn btn-primary btn-lg btn-block']) !!}


            {!! Form::close() !!}

        </div>
    </div>



    @endsection

resources/views/comments/comment.blade.php
@extends('layouts.theme')

@section('working_area')

    <div class="col-lg-6">
        <div class="card-box col-md-offset-3">
            {!! Form::open(['route'=>'article.store','class'=>'form form-horizontal']) !!}

            <div class="form-group {{ $errors->has('body') ? ' has-error' : '' }}">

                {!! Form::label('body','Comment',null,['class'=>'control-label']) !!}
                {!! Form::textarea('body',null,['class'=>'form-control']) !!}
                @if ($errors->has('body'))
                    <span class="help-block">
                                        <strong>{{ $errors->first('body') }}</strong>
                                    </span>
                @endif
            </div>
            {!! Form::submit('Submit Comment',['class'=>'btn btn-primary btn-lg btn-block']) !!}


            {!! Form::close() !!}

        </div>
    </div>



@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="/css/app.css" rel="stylesheet">

    <!-- Scripts -->
    <script>
        window.Laravel = <?php echo json_encode([
            'csrfToken' => csrf_token(),
        ]); ?>
    </script>
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        {{ config('app.name', 'Laravel') }}
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @if (Auth::guest())
                            <li><a href="{{ url('/login') }}">Login</a></li>
                            <li><a href="{{ url('/register') }}">Register</a></li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="{{ url('/logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endif
                    </ul>
                </div>
            </div>
        </nav>

        @yield('content')
    </div>

    <!-- Scripts -->
    <script src="/js/app.js"></script>
</body>
</html>

resources/views/layouts/theme.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--Morris Chart CSS -->
    <link rel="stylesheet" href="{{URL::asset('assets/plugins/morris/morris.css')}}">

    <link href="{{URL::asset('assets/css/bootstrap.min.css')}}" rel="stylesheet" type="text/css" />
    <link href="{{URL::asset('assets/css/menu.css')}}" rel="stylesheet" type="text/css" />
    <link href="{{URL::asset('assets/css/core.css')}}" rel="stylesheet" type="text/css" />
    <link href="{{URL::asset('assets/css/components.css')}}" rel="stylesheet" type="text/css" />
    <link href="{{URL::asset('assets/css/icons.css')}}" rel="stylesheet" type="text/css" />
    <link href="{{URL::asset('assets/css/pages.css')}}" rel="stylesheet" type="text/css" />
    <link href="{{URL::asset('assets/css/responsive.css')}}" rel="stylesheet" type="text/css" />
    <link href="{{URL::asset('css/animate.css')}}" rel="stylesheet" type="text/css" />
    <link href="{{URL::asset('css/custom.css')}}" rel="stylesheet" type="text/css" />

    <!-- HTML5 Shiv and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->

    <script src="{{URL::asset('assets/js/modernizr.min.js')}}"></script>

</head>
<body class="fixed-left">

<!-- Begin page -->
<div id="wrapper">
    @include('shared.navbar')
    @include('shared.sidebar')
    <!-- Start content -->
    <div class="content-page">

        <div class="content">
            <div class="container">
                <!--Our notification system-->
                @include('shared.noty')
                @yield('working_area')
            </div>
        </div>
    </div>

</div>














<script>
    var resizefunc = [];
</script>

<!-- jQuery  -->
<script src="{{URL::asset("assets/js/jquery.min.js")}}"></script>
<script src="{{URL::asset("assets/js/bootstrap.min.js")}}"></script>
<script src="{{URL::asset("assets/js/detect.js")}}"></script>
<script src="{{URL::asset("assets/js/fastclick.js")}}"></script>
<script src="{{URL::asset("assets/js/jquery.slimscroll.js")}}"></script>
<script src="{{URL::asset("assets/js/jquery.blockUI.js")}}"></script>
<script src="{{URL::asset("assets/js/waves.js")}}"></script>
<script src="{{URL::asset("assets/js/wow.min.js")}}"></script>
<script src="{{URL::asset("assets/js/jquery.nicescroll.js")}}"></script>
<script src="{{URL::asset("assets/js/jquery.scrollTo.min.js")}}"></script>

<!--Morris Chart-->
<script src="{{URL::asset("assets/plugins/morris/morris.min.js")}}"></script>
<script src="{{URL::asset("assets/plugins/raphael/raphael-min.js")}}"></script>

<!-- Counter Up  -->
<script src="{{URL::asset("assets/plugins/waypoints/lib/jquery.waypoints.js")}}"></script>
<script src="{{URL::asset("assets/plugins/counterup/jquery.counterup.min.js")}}"></script>

<!-- Dashboard init -->
<script src="{{URL::asset("assets/pages/jquery.dashboard.")}}"></script>


<!-- App js -->
<script src="{{URL::asset("assets/js/jquery.core.js")}}"></script>
<script src="{{URL::asset("assets/js/jquery.app.js")}}"></script>
<script src="{{URL::asset("js/custom.js")}}"></script>
</body>
</html>

resources/views/shared/navbar.blade.php
<!-- Top Bar Start -->
<div class="topbar">

    <!-- LOGO -->
    <div class="topbar-left">
        <div class="text-center">
            <a href="index.html" class="logo">
                <i class="zmdi zmdi-toys icon-c-logo"></i><span>Blog<span>In</span></span>
                <!--<span><img src="assets/images/logo.png" alt="logo" style="height: 20px;"></span>-->
            </a>
        </div>
    </div>

    <!-- Button mobile view to collapse sidebar menu -->
    <div class="navbar navbar-default" role="navigation">
        <div class="container">
            <div class="">
                <div class="pull-left">
                    <button class="button-menu-mobile open-left waves-effect waves-light">
                        <i class="zmdi zmdi-menu"></i>
                    </button>
                    <span class="clearfix"></span>
                </div>

                <form role="search" class="navbar-left app-search pull-left hidden-xs">
                    <input type="text" placeholder="Search..." class="form-control">
                    <a href=""><i class="fa fa-search"></i></a>
                </form>


                <ul class="nav navbar-nav navbar-right pull-right">
                    <li>
                        <!-- Notification -->
                        <div class="notification-box">
                            <ul class="list-inline m-b-0">
                                <li>
                                    <a href="javascript:void(0);" class="right-bar-toggle">
                                        <i class="zmdi zmdi-notifications-none"></i>
                                    </a>
                                    <div class="noti-dot">
                                        <span class="dot"></span>
                                        <span class="pulse"></span>
                                    </div>
                                </li>
                            </ul>
                        </div>
                        <!-- End Notification bar -->
                    </li>

                    <li class="dropdown user-box">
                        <a href="" class="dropdown-toggle waves-effect waves-light profile " data-toggle="dropdown" aria-expanded="true">
                            <img src="assets/images/users/avatar-1.jpg" alt="user-img" class="img-circle user-img">
                            <div class="user-status away"><i class="zmdi zmdi-dot-circle"></i></div>
                        </a>

                        <ul class="dropdown-menu">
                            @if(!Auth::guest())
                            <li><a href="javascript:void(0)"><i class="ti-user m-r-5"></i> {{Auth::user()->name}}</a></li>
                            @endif
                            <li><a href="javascript:void(0)"><i class="ti-settings m-r-5"></i> Settings</a></li>
                            <li><a href="javascript:void(0)"><i class="ti-lock m-r-5"></i> Lock screen</a></li>
                            <li><a href="{{ url('/logout') }}"
                                   onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                    <i class="ti-power-off m-r-5"></i> Logout
                                    </a>

                                <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
                                    {{ csrf_field() }}
                                </form></li>
                        </ul>
                    </li>
                </ul>

            </div>
            <!--/.nav-collapse -->
        </div>
    </div>
</div>
<!-- Top Bar End -->

resources/views/shared/noty.blade.php
@if(Session::has('success'))
<div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <strong>Great!</strong> {{Session::get('success')}}
</div>
    @endif

@if(Session::has('error'))
    <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <strong>Great!</strong> {{Session::get('success')}}
    </div>
@endif

resources/views/shared/sidebar.blade.php
<!-- ========== Left Sidebar Start ========== -->

<div class="left side-menu">
    <div class="sidebar-inner slimscrollleft">
        <!--- Divider -->
        <div id="sidebar-menu">
            <ul>

                <li class="text-muted menu-title">Navigation</li>

                <li class="has_sub">
                    <a href="{{url(route('article.index'))}}" class="waves-effect"><i class="fa fa-home"></i> <span> Home </span> </a>
                </li>

                <li class="has_sub">
                    <a href="javascript:void(0);" class="waves-effect"><i class="fa fa-newspaper-o"></i> <span> Articles </span> <span class="menu-arrow"></span> </a>
                    <ul class="list-unstyled">
                        <li><a href="{{url(route('article.create'))}}">Create new</a></li>
                        <li><a href="{{url(route('article.index'))}}">All Articles</a></li>

                    </ul>
                </li>
                <li class="has_sub">
                    <a href="javascript:void(0);" class="waves-effect"><i class="fa fa-comments"></i> <span> Comment </span> <span class="menu-arrow"></span> </a>
                    <ul class="list-unstyled">
                        <li><a href="">View Comments</a></li>


                    </ul>
                </li>



            </ul>
            <div class="clearfix"></div>
        </div>
        <div class="clearfix"></div>

    </div>
</div>
<!-- Left Sidebar End -->